#CANALES
DINERO_INICIAL = 200
COBRO_USO_PRINCIPIANTE = 5
COBRO_USO_AVANZADO = 10
COSTO_DESENCALLAR = 5
PROB_BASE_DESENCALLAR = 10
PONDERADOR_PRINCIPIANTE = 1
PONDERADOR_AVANZADO = 2
PROB_BASE_DESENCALLAR = 0.9

#BARCOS
TENDENCIA_ENCALLAR_PASAJEROS = 1
TENDENCIA_ENCALLAR_CARGUERO = 2
TENDENCIA_ENCALLAR_BUQUE = 3
DINERO_INTOXICACION = 2
TIEMPO_AVERIA_BUQUE = 1

#TRIPULANTES
CARGA_EXTRA_CARGUERO = 40

PROBABILIDAD_MAX = 1
# calculo la probabilidad de True con las formulas
# luego la probabiliad de False es PROBABILIDAD_MAX - prob_True
# ENTONCES ESTE PARAMETRO SIRVE PARA VER SI LA PROBABILIDA EN TOTAL VALE 1, 10, 100, ETC.